load_path: "" # only used when separately evaluating a pretrained model
eval: true
batch_size: 64
num_workers: 0
n_eval: 50
eval_every: 10
max_steps: 600
use_mp: true
num_procs: 10
save_sim_states: false
